export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const START_GET_CATEGORIES = 'START_GET_CATEGORIES';
export const SUCCESS_GET_CATEGORIES = 'SUCCESS_GET_CATEGORIES';
export const FAIL_GET_CATEGORIES = 'FAIL_GET_CATEGORIES';